routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('user/change-status/{id}/{status}', 'UserController@changeStatus')->name('user.change-status');
Route::resource('user', 'UserController');
Route::resource('/', 'UserController');
Route::resource('home', 'MagazineController');

Route::get('article/change-status/{id}/{status}', 'ArticleController@changeStatus')->name('article.change-status');
Route::resource('article', 'ArticleController');

Route::get('magazine/change-status/{id}/{status}', 'MagazineController@changeStatus')->name('magazine.change-status');
Route::get('magazine/change-status-buyable/{id}/{status}', 'MagazineController@changeStatusBuyable')->name('magazine.change-status-buyable');
Route::get('magazine/bundling/{id}', 'MagazineController@sendBundling')->name('magazine.send-bundling');
Route::resource('magazine', 'MagazineController');

Route::get('register-transaction', 'CustomerController@registerTransaction')->name('customer.register-transaction');
Route::post('register-transaction', 'CustomerController@processRegisterTransaction')->name('customer.process-register-transaction');
Route::get('customer/change-status/{id}/{status}', 'CustomerController@changeStatus')->name('customer.change-status');
Route::resource('customer', 'CustomerController');

Route::get('webinar/change-status/{id}/{status}', 'WebinarController@changeStatus')->name('webinar.change-status');
Route::resource('webinar', 'WebinarController');

Route::get('slider/change-status/{id}/{status}', 'SliderController@changeStatus')->name('slider.change-status');
Route::resource('slider', 'SliderController');

Route::get('podcast/change-status/{id}/{status}', 'PodcastController@changeStatus')->name('podcast.change-status');
Route::resource('podcast', 'PodcastController');

Route::get('youtube/change-status/{id}/{status}', 'YoutubeController@changeStatus')->name('youtube.change-status');
Route::resource('youtube', 'YoutubeController');

Route::resource('bundling', 'BundlingController');

Route::resource('static-content', 'StaticContentController');


Route::get('download/{transactionId}/{purchaseCode}/{type}', 'HomeController@download')->name('download');
Route::get('download-bundling/{transactionId}/{type}', 'HomeController@downloadSubscriber')->name('download.subscriber');

Route::get('transaction/change-status/{id}/{status}', 'TransactionController@changeStatus')->name('transaction.change-status');
Route::get('transaction/send-link/{id}', 'TransactionController@sendLink')->name('transaction.send-link');
Route::get('transaction/send-bundling/{id}', 'MagazineController@sendBundlingExisted')->name('transaction.send-bundling-existed');
Route::get('transaction/register-bundling/{customerId}/{magazineId}', 'MagazineController@sendBundlingRegister')->name('transaction.send-bundling-register');
Route::get('transaction/export', 'TransactionController@export')->name('transaction.export');
Route::resource('transaction', 'TransactionController');

resources/views/layout/breadcrumb.blade.php
<!-- Content Header (Page header) -->
<section class="content-header">
	  @if(isset($title))
  <h1>{{ ucwords(str_replace('-',' ', $title)) }}</h1>
  @else
  <h1>{{ (isset($page)) ? ucwords(str_replace('-',' ', $page)) : 'Dashboard' }}</h1>
  @endif
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">{{ (isset($page)) ? ucwords($page) : 'Dashboard' }}</li>
  </ol>
</section>

resources/views/layout/css-global.blade.php
<link rel="stylesheet" href="{{asset('lte/bower_components')}}/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('lte/bower_components')}}/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{asset('lte/bower_components')}}/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('lte')}}/css/AdminLTE.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ==" crossorigin="anonymous" />
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{asset('lte')}}/css/skins/_all-skins.min.css">

  @include('layout.css-local')

  <link rel="stylesheet" href="{{ asset('lte') }}/css/custom.css?v=0.5">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/layout/css-local.blade.php
@if(isset($localAsset))
	@foreach($localAsset as $key => $val)
		@includeIf('util.css.'.$val)
	@endforeach
@endif

@includeIf($local_css_path.$page)

resources/views/layout/footer.blade.php
<footer class="main-footer">
	<div class="pull-right hidden-xs">
	  <b>Version</b> 2.4.0
	</div>
	<strong>Copyright © 2020 - All Rights Reserved</strong> 
	All rights reserved.
</footer>

resources/views/layout/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">
        
      </span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">
        <b>{{config("app.name")}}</b>
      </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can bepside found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs">{{$user['name']}}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{{route('user.edit', ['id' => Auth::id()])}}?type=profile" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{{url('/logout')}}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

resources/views/layout/js-global.blade.php
<!-- jQuery 3 -->
<script src="{{asset('lte/bower_components')}}/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('lte/bower_components')}}/jquery-ui/jquery-ui.min.js"></script>

<!-- Bootstrap 3.3.7 -->
<script src="{{asset('lte/bower_components')}}/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- AdminLTE App -->
<script src="{{asset('lte')}}/js/adminlte.min.js"></script>

<script src="{{ asset('lte') }}/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="{{ asset('lte') }}/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

<script>
  $(function () {
    $('#example1').DataTable({
    	"order":[[0, 'desc']]
    })

    $( "#datepicker" ).datepicker({
      "dateFormat":"yy-mm-dd"
    });
    $( "#datepicker_birthdate" ).datepicker({
      "dateFormat":"yy-mm-dd",
      "changeMonth":true,
      "changeYear":true,
      "maxDate":new Date(),
      "yearRange": '1970:2050'
    });
    $( "#datepicker2" ).datepicker({
      "dateFormat":"yy-mm-dd"
    });
  })
</script>

@include('layout.js-local')

resources/views/layout/js-local.blade.php
@if(isset($localAsset))
	@foreach($localAsset as $key => $val)
		@includeIf('util.js.'.$val)
	@endforeach
@endif

@includeIf($local_js_path.$page)

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html>
  <head>

    <!-- META -->
    @include("layout.meta")

    <!-- CSS -->
    @include("layout.css-global")

  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- HEADER -->
      @include("layout.header")  

      <!-- SIDEBAR -->
      @include("layout.sidebar")    

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">

        <!-- SIDEBAR -->
        @include("layout.sidebar")    

        @yield("content")
        <div style="clear: both;"></div>
      
      </div>

      <!-- SIDEBAR -->
      @include("layout.footer")    

    </div>

    <!-- SIDEBAR -->
    @include("layout.js-global")      

  </body>
</html>

resources/views/layout/meta.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{{config("app.name")}} CMS</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

resources/views/layout/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li @if($page == 'user') class="active" @endif>
          <a href="{{route('user.index')}}">
          <i class="fa fa-users"></i> <span>User</span>
          </a>
        </li>

        <li @if($page == 'bundling') class="active" @endif>
          <a href="{{route('bundling.index')}}">
          <i class="fa fa-money"></i> <span>Bundling</span>
          </a>
        </li>

        <li @if($page == 'article') class="active" @endif>
          <a href="{{route('article.index')}}">
          <i class="fa fa-image"></i> <span>Blog</span>
          </a>
        </li>

        <li @if($page == 'podcast') class="active" @endif>
          <a href="{{route('podcast.index')}}">
          <i class="fa fa-music"></i> <span>Podcast</span>
          </a>
        </li>

        <li @if($page == 'youtube') class="active" @endif>
          <a href="{{route('youtube.index')}}">
          <i class="fa fa-play"></i> <span>Youtube</span>
          </a>
        </li>

        <li @if($page == 'magazine') class="active" @endif>
          <a href="{{route('magazine.index')}}">
          <i class="fa fa-image"></i> <span>Magazine</span>
          </a>
        </li>

        <li @if($page == 'customer') class="active" @endif>
          <a href="{{route('customer.index')}}">
          <i class="fa fa-users"></i> <span>Customer</span>
          </a>
        </li>

        <li @if($page == 'transaction') class="active" @endif>
          <a href="{{route('transaction.index')}}">
          <i class="fa fa-money"></i> <span>Transaction</span>
          </a>
        </li>

        <li @if($page == 'customer') class="active" @endif>
          <a href="{{route('customer.register-transaction')}}">
          <i class="fa fa-money"></i> <span>Register User Transaction</span>
          </a>
        </li>

        <li @if($page == 'static-content') class="active" @endif>
          <a href="{{route('static-content.index')}}">
          <i class="fa fa-pencil"></i> <span>Static Content</span>
          </a>
        </li>
        
        <li @if($page == 'webinar') class="active" @endif>
          <a href="{{route('webinar.index')}}">
          <i class="fa fa-money"></i> <span>Webinar</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>